server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/game_community?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: 20031111
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.example.com        # SMTP服务器地址
    port: 587                     # SMTP端口，常用587或465
    username: email@example.com  # SMTP账号
    password: password       # SMTP密码
    properties:
      mail:
        smtp:
          auth: true             # 启用SMTP认证
          starttls:
            enable: true         # 启用STARTTLS加密

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 60000

jwt:
  secret: 1145141919810
  expiration: 86400000 # 24 hours

  # 文件上传路径配置
upload:
  path: ./uploads
  max-size: 10485760  # 10MB
  allowed-types:
    - image/jpeg
    - image/png
    - image/gif

logging:
  level:
    root: INFO
    com.gameplatform: DEBUG
    org.springframework.security: DEBUG


